### PR TITLE
removing the unnecessary previous call in setState

### PR DESCRIPTION
**Pull request by kaungphyowai**
@yaungnilinn  I find the code. Plz check if this is ok to merge

### CODE REVIEW

**Comment by yaungnilinn** [comment]
is ok to merge but plz delete console.log in master branch

**Comment by yaungnilinn** [comment]
noti test

**Comment by kaungphyowai** [comment]
> is ok to merge but plz delete console.log in master branch

Sorry My mistake. I will change it and will commit it

**Comment by kaungphyowai** [comment]
How about now? Is Everything ok to merge? @yaungnilinn

**Comment by yaungnilinn** [comment]
is ok to merge now and plz close this pull request now

**Comment by kaungphyowai** [comment]
> is ok to merge now and plz close this pull request now

Ok thanks for the review

**Comment by kaungphyowai** [comment]
Sorry. My Mistke. I will do that.

**Pull request merged**
